### ISSUE TITLE
为什么英文字体压缩后与之前不同

### ISSUE THREAD

**Issue by zbh876325764** [ecomfe/fontmin#100]
为什么压缩后渲染效果不同? 我输出和输入都是ttf格式.所以需要我更改格式么?

例子使用的是calibri.ttf
黑色是压缩前 红色是压缩后
![image](https://user-images.githubusercontent.com/42517813/145770706-fde81bb0-e621-4954-a788-e59537a1a39e.png)
![image](https://user-images.githubusercontent.com/42517813/145770967-9c095907-539e-48a6-ac71-2cb956e4bc13.png)

**Comment by yisibl** [comment]
这里的原版字体看起来使用了连字特性，而 fontmin 似乎不支持裁剪后保留连字的特性，所以字母就分开了。
