### ISSUE TITLE
fontmin 使字体清晰度下降

### ISSUE THREAD

**Issue by randoms** [ecomfe/fontmin#11]
未使用fontmin的字体显示
![Image of 感](http://randoms.me/media/img/origin.PNG)
使用后的字体显示
![Image of 感](http://randoms.me/media/img/processed.PNG)
是不是fontmin默认采用了什么字体压缩之类的，能不能设置取消?
Thanks

**Comment by benluo** [comment]
我和你的观点相反。我觉得第二个更清晰。但我的结论是第一个用了反锯齿，第二 
个没用。

**Comment by randoms** [comment]
这两个都没设置反锯齿，都是一样的css。
我发现不是所有的字体都是这样，我换了一种隶书的字体，就没有这种锯齿现象了。原来是方正隶属简体。

**Comment by junmer** [comment]
请问 系统是否是 windows ?
压缩前 是否使用的是本地字体 ？
windows 对 webfont 的渲染效果，其实。。。 不大好

可以参考
 [A Closer Look At Font Rendering](http://www.smashingmagazine.com/2012/04/24/a-closer-look-at-font-rendering/)

**Comment by randoms** [comment]
我没有使用本地字体，都是webfont。 不过我没有换系统测试。我觉得可能是那个字体文件有些问题吧。
