### ISSUE TITLE
Will Fontmin-osx64 continue to be updated?

### ISSUE THREAD

**Issue by MALTF** [ecomfe/fontmin#112]
![Fontmin-v0.2.0-osx64](https://cloud.githubusercontent.com/assets/157338/7086319/fee1246a-dfb1-11e4-9be7-b0e8dd007f59.png)
[下载 Fontmin App 发行版](https://github.com/ecomfe/fontmin-app/releases) Apr 16, 2015 后续还会更新吗？

**Comment by kekee000** [comment]
暂时没有计划，欢迎提 pr。
