### ISSUE TITLE
压缩谷歌字体时报错: TypeError: Cannot read property 'contours' of undefined

### ISSUE THREAD

**Issue by duheng1992** [ecomfe/fontmin#114]
字体名称：MaShanZheng-Regular.ttf

导出场景：macos客户端
<img width="842" alt="企业微信截图_383dae7b-94dc-40d2-9ef6-ba9f25a701ec" src="https://github.com/ecomfe/fontmin/assets/22112227/6edbe511-4403-486d-8c4d-f4aa381eb871">

**Comment by duheng1992** [comment]
补充：客户端版本号 0.2.0

**Comment by kekee000** [comment]
客户端很久没维护了，建议 fontmin 命令行模式，也很方便
