### ISSUE TITLE
react项目中引入fontmin 编译报错

### ISSUE THREAD

**Issue by coderi521** [ecomfe/fontmin#119]
![D-Chat_20240814201604](https://github.com/user-attachments/assets/71e53d7d-feed-454b-9507-24d1d836e16e)

**Comment by coderi521** [comment]
![Uploading img.png…]()

**Comment by yangyu521** [comment]
node版本 14.19.3
可以随便使用vue或者react创建一个demo，引入fontmin就会报错，猜测原因是fontmin中还有一些依赖中用到了fs(node下的api)，所以想确定下fontmin是不支持浏览器环境下裁剪嘛，我现在是想在浏览器环境下，生成ttf、woff、woff2的裁剪文件，目前卡在依赖报错上了。
示例：
const Fontmin = require("fontmin");
export function minifyFont() {
  return new Fontmin()
} // 报错

**Comment by kekee000** [comment]
fontmin 不支持 浏览器环境，可以使用 fonteditor-core 模块，支持 ttf 裁剪，具体示例参考 test case。

**Comment by yangyu521** [comment]
好的，感谢啦～




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ecomfe/fontmin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月21日(星期一) 中午11:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ecomfe/fontmin] react项目中引入fontmin 编译报错 (Issue #119)





 
fontmin 不支持 浏览器环境，可以使用 fonteditor-core 模块，支持 ttf 裁剪，具体示例参考 test case。
