### ISSUE TITLE
[ReferenceError: glyph is not defined]

### ISSUE THREAD

**Issue by LjxPrime** [ecomfe/fontmin#12]
I'm just testing with the sample code:
<pre><code>
var Fontmin = require('fontmin');

var srcPath = 'src/font/*.ttf'; // 字体源文件
var destPath = 'asset/font';    // 输出路径
var text = '我说你是人间的四月天；笑响点亮了四面风；轻灵在春的光艳中交舞着变。';

// 初始化
var fontmin = new Fontmin()
    .src(srcPath)               // 输入配置
    .use(Fontmin.glyph({        // 字型提取插件
        text: text              // 所需文字
    }))
    .use(Fontmin.ttf2eot())     // eot 转换插件
    .use(Fontmin.ttf2woff())    // woff 转换插件     
    .use(Fontmin.ttf2svg())     // svg 转换插件
    .use(Fontmin.css())         // css 生成插件
    .dest(destPath);            // 输出配置

// 执行
fontmin.run(function (err, files, stream) {

    if (err) {                  // 异常捕捉
        console.error(err);
    }

    console.log('done');        // 成功
});
</code></pre>
The ERR msg is <pre><code> [ReferenceError: glyph is not defined]</code></pre>
and I only get a ttf and a css file. And both of them are not generated correctly.

**Comment by junmer** [comment]
hi @LjxPrime , can u provide the ttf file.
the err
> [ReferenceError: glyph is not defined]

usually happen when otf file but filename is `.ttf`

you can use [is-ttf](https://github.com/junmer/is-ttf) to detect

**Comment by rayliao** [comment]
我也遇到这个问题。
![qq 20151031113741](https://cloud.githubusercontent.com/assets/5601068/10861670/d2cf1e60-7fc3-11e5-8502-7bd8cf0c3c6b.jpg)

````
gulp.task('fontmin', function (){
    var Fontmin = require('fontmin');

    var srcPath = 'app/fonts/origin/SentySnowMountain.ttf'; // 字体源文件
    var destPath = 'app/fonts';    // 输出路径
    var text = '我说你是人间的四月天；笑响点亮了四面风；轻灵在春的光艳中交舞着变。';

    var fs = require('fs');
    var isTtf = require("is-ttf");
    console.log(isTtf(fs.readFileSync(srcPath)));
    // 初始化
    var fontmin = new Fontmin()
        .src(srcPath)               // 输入配置
        // .use(Fontmin.glyph({        // 字型提取插件
        //     text: text              // 所需文字
        // }))
        // .use(Fontmin.ttf2eot())     // eot 转换插件
        // .use(Fontmin.ttf2woff())    // woff 转换插件     
        // .use(Fontmin.ttf2svg())     // svg 转换插件
        // .use(Fontmin.css({
        //     base64: true
        // }))
        .dest(destPath);            // 输出配置

    // 执行
    fontmin.run(function (err, files, stream) {

        if (err) {                  // 异常捕捉
            console.error(err);
        }

        console.log('done');        // 成功
    });
});
````

**Comment by rayliao** [comment]
````
.use(Fontmin.css({
        base64: true,
        glyph: true
}))
````
这里glyph设为true就不会了，为什么？前面我直接输出也有用到glyph的插件吗？
