### ISSUE TITLE
Error: EROFS: read-only file system怎么解决？！

### ISSUE THREAD

**Issue by Zachary-zyt** [ecomfe/fontmin#120]
<img width="843" alt="截屏2024-08-23 11 27 18" src="https://github.com/user-attachments/assets/a5ad65d5-ddd3-49f8-9430-2124a79fc74a">
Error: EROFS: read-only file system
这个问题怎么解决呀

**Comment by kekee000** [comment]
把 app 移动到 applications 目录，或者有写权限的目录就可以了。

**Comment by Zachary-zyt** [comment]
您好，我最近正在学习奋斗中，可能无法及时回复您的邮件。我会在工作结束后，尽快给您回复！

**Comment by Zachary-zyt** [comment]
您好，我最近正在学习奋斗中，可能无法及时回复您的邮件。我会在工作结束后，尽快给您回复！
