### ISSUE TITLE
无法识别MSTIFFHEIPRC-ULTRABOLD.TTF字体

### ISSUE THREAD

**Issue by kasyman** [ecomfe/fontmin#16]
引入这个字体文件的时候，能够生成文本片段的预览效果，但无法生成文件。
会报这个错误：“not support cmap format:2”

**Comment by junmer** [comment]
@kasyman hi, 可否提供一下字体文件，我们定位一下问题 谢谢 :smiley:

**Comment by junmer** [comment]
原因同 https://github.com/ecomfe/fontmin/issues/20 
合并 issue
