### ISSUE TITLE
'严'和'霾'冲突

### ISSUE THREAD

**Issue by flashlizi** [ecomfe/fontmin#2]
hi，

我使用fontmin压缩字体`方正兰亭纤黑简体.ttf`时出错，后来发现只要`严`和`霾`字同时出现就会出错。

**Comment by junmer** [comment]
你好 可以把 错误信息打出啦么

**Comment by flashlizi** [comment]
最开始我直接用grunt-fontmin的时候会报错`check sum out of bound`，后来从github拉了新fontmin后不报错了，但是，输出的字体内容不是预期的内容，要么产品的ttf文件直接打不开，要么输出的字形只有1-2个。貌似还是之前那个校验码出错导致的问题。

**Comment by junmer** [comment]
您说的是 `gulp-fontmin` 吧？ 那个我还没写完。
方正兰亭 我测试过 应该是可以的

**Comment by flashlizi** [comment]
补充问题测试case：

* 字体：方正兰亭纤黑简体.ttf 
* 只输出如下3个字形：`雾霾，`
* 结果：字体输出成功了，预览也ok，但是在chrome下页面却crash了，去掉逗号就好了。

**Comment by junmer** [comment]
@flashlizi  刚刚发布了 [0.7.3](https://www.npmjs.com/package/fontmin) 
请看一下 是否解决了 你的问题
```
npm i -g fontmin@0.7.3
fontmin filename -t "雾霾，"
```

谢谢

**Comment by junmer** [comment]
@flashlizi 从经验上看，crash 的原因基本上是 hint 信息的问题，同 #6 ，已经解决。这个 ISSUE 可以关闭了么？
