### ISSUE TITLE
如果某些字不在原始文件中报错 check sum out of bound

### ISSUE THREAD

**Issue by wavelynn** [ecomfe/fontmin#28]
原始字体 HappyZcool.ttf，text="某些文字"，执行fontmin后得到新文件 HappyZcool_small.ttf，执行执行fontmin操作，此时如果text文字不在第一次的text中时就会报错 check sum out of bound

**Comment by junmer** [comment]
多谢反馈，下个版本处理一下
但是，还是提醒一下 保留原始字体文件哦

**Comment by luxueyan** [comment]
用0.9.0-alpha 就没这个问题 希望尽快解决一下

**Comment by junmer** [comment]
fixed
see [CHANGELOG](https://github.com/ecomfe/fontmin/blob/master/CHANGELOG.md#093-2016-4-6)
谢谢
