### ISSUE TITLE
部分字体在 font-size 比较小的时，修正信息丢失

### ISSUE THREAD

**Issue by junmer** [ecomfe/fontmin#4]
case 如下

[font-spider：转换的字体在某些浏览器中显示不全](https://github.com/aui/font-spider/issues/23)
[知乎：Safari下嵌入中文字体导致的缺少笔画是如何产生的？](http://www.zhihu.com/question/29556294)

可能原因

hint 信息 未处理 @kekee000 

参考

<https://developer.apple.com/fonts/TrueType-Reference-Manual/RM02/Chap2.html#size>
<https://developer.apple.com/fonts/TrueType-Reference-Manual/RM02/Chap2.html#where>

**Comment by kekee000** [comment]
hintting信息导出的时候会被移除，在下一版中会添加hinting信息，可以解决字体较小时发糊的情况。

**Comment by junmer** [comment]
e46e3c51d4f1d387601c8aee1fd8176d841a4b57 done
