### ISSUE TITLE
思源黑体 ExtraLight 无法使用怎么回事儿了？

### ISSUE THREAD

**Issue by qdsang** [ecomfe/fontmin#7]
字体文件： http://pan.baidu.com/s/1bnxr99P 密码：fkxb

生成后只有ttf字体源文件， 感觉是无法识别这个ttf字体文件， 在系统中使用无异常， 其他地方下载同样。

**Comment by junmer** [comment]
@qdsang 我看了一下
```
<File "SourceHanSansCN-ExtraLight.TTF" <Buffer 4f 54 54 4f 00 10 01 00 00 04 00 00 42 41 53 45 1b 8e 18 d8 00 75 8e 3c 00 00 00 e4 43 46 46 20 2d 8f d3 b8 00 00 95 1c 00 70 69 74 44 53 49 47 00 00 ... >>
```

这实际是个 OTF

see: [file-type](https://github.com/sindresorhus/file-type/blob/master/index.js#L254)

附 思源 TTF: http://pan.baidu.com/s/1gdrMurh

OTF 的支持在开发中， 先用上面的吧 :smiley:

**Comment by qdsang** [comment]
250M+ 赞~   3Q

**Comment by joenil** [comment]
@junmer 我也遇到了这个问题，想试一下你盘里的字体文件，但是分享不见了。
